--Excel 2 txt using Scala
--Excel file: Test1.xlsx
--Executed on: 2016-04-18
INSERT INTO TABLE_NAME (NUMBERS, BIG_NUMBERS, DECIMALS, STRINGS, LANGUAGES, FIXED_VALUE) VALUES(1.0,1000.0,1001.0,'AAA','JAVA','FIXED');
INSERT INTO TABLE_NAME (NUMBERS, BIG_NUMBERS, DECIMALS, STRINGS, LANGUAGES, FIXED_VALUE) VALUES(2.0,1000.0,1002.0,'BBB','SCALA','FIXED');
INSERT INTO TABLE_NAME (NUMBERS, BIG_NUMBERS, DECIMALS, STRINGS, LANGUAGES, FIXED_VALUE) VALUES(3.0,1000.0,1003.0,'CCC','GROOVY','FIXED');
INSERT INTO TABLE_NAME (NUMBERS, BIG_NUMBERS, DECIMALS, STRINGS, LANGUAGES, FIXED_VALUE) VALUES(4.0,1000.0,1004.0,'DDD','CLOJURE','FIXED');
INSERT INTO TABLE_NAME (NUMBERS, BIG_NUMBERS, DECIMALS, STRINGS, LANGUAGES, FIXED_VALUE) VALUES(5.0,1000.0,1005.0,'EEE','OUT OF OPTIONS','FIXED');
INSERT INTO TABLE_NAME (NUMBERS, BIG_NUMBERS, DECIMALS, STRINGS, LANGUAGES, FIXED_VALUE) VALUES(6.0,1000.0,1006.0,'FFF',NULL,'FIXED');
INSERT INTO TABLE_NAME (NUMBERS, BIG_NUMBERS, DECIMALS, STRINGS, LANGUAGES, FIXED_VALUE) VALUES(7.0,1000.0,1007.0,'GGG',NULL,'FIXED');
INSERT INTO TABLE_NAME (NUMBERS, BIG_NUMBERS, DECIMALS, STRINGS, LANGUAGES, FIXED_VALUE) VALUES(8.0,1000.0,1008.0,'HHH',NULL,'FIXED');
INSERT INTO TABLE_NAME (NUMBERS, BIG_NUMBERS, DECIMALS, STRINGS, LANGUAGES, FIXED_VALUE) VALUES(9.0,1000.0,1009.0,'III',NULL,'FIXED');
INSERT INTO TABLE_NAME (NUMBERS, BIG_NUMBERS, DECIMALS, STRINGS, LANGUAGES, FIXED_VALUE) VALUES(10.0,1000.0,1010.0,'LLL',NULL,'FIXED');
